# Lista de Exercícios de Numpy

Deverá ser entrege até **11/02/2023** por meio do github que foi informado por vocês no [formulário](https://forms.office.com/r/YV12vEXGYF) respondido na aula de 01/02.

A entrega pela github é parte da avaliação.

## Questão 1

Crie um array 100 com valores aleatórios e ache os valores máximo e mínimo

In [ ]:
import numpy as np

_array = np.random.randint(0,1001,100)
print(_array)
print(f'O maior valor do array é: {np.amax(_array)}')
print(f'O menor valor do array é: {np.amin(_array)}')

[324 309  37 904  60  94 232 788 547 512 149 470 214 398 557 576   5 935
 930  80 188 662 659  27 676 977 134 765 304 494 723 279  79 780 859 390
  14 598 918 891 222 836 602 827 265 818 319 105 252 198  55 927 406 437
 750 456 476 346 485 852 362 965 729 211 700 846 876 613 915 436 142 284
  69 847 576 957 709 527 309 864 262  59 521 308 519 381 340 601 548 977
 899  83 233 761 239 103 722 224 278 392]
O maior valor do array é: 977
O menor valor do array é: 5


## Questão 2
Em Geometria Analítica, um **vetor** é uma quantidade que pode ser definida por um énuplo (uma sequência ordenada de *n* elementos) em que cada elemento representa a intensidade do vetor na direção especificada pela i-ésima componente desta sequência. 

Quando pensamos em duas dimensões, por exemplo, o vetor $R = (b,a)$ define, geometricamente, a entidade representada na figura abaixo, com componentes nos eixos x e y usuais.

<img src = "https://static.todamateria.com.br/upload/im/ag/image-721.jpg?auto_optimize=low" />

O **módulo** deste vetor, também chamado de intensidade, está geometricamente relacionado ao seu comprimento, e pode ser calculado diretamente pelas suas componentes, por meio de uma operação conhecida como **produto escalar** do vetor com ele mesmo. O módulo quadrático é expresso, desta forma, por:

$|A|^2 = \vec{A} \cdot \vec{A}$

Por outro lado, o produto escalar entre dois vetores $A = (a_{x}, a_{y})$ e $B = (b_{x}, b_{y})$ é dado por:

$\vec{A} \cdot \vec{B} = a_{x} \times b_{x} + a_{y} \times b_{y}$ (e esta definição vale para qualquer que seja a dimensão do vetor).

O módulo quadrático de um vetor é, portanto:

$|A|² = a_{x}^2 + b_{x}^2$.

Dado o exposto acima, escreva uma função que retorne o módulo de um vetor n-dimensional qualquer.

In [ ]:
import numpy as np

def modulo(vetor):
  return np.sqrt((np.sum(vetor**2)))

dim = int(input('Qual a dimensão do vetor?'))
vetor = np.random.randint(0,100,dim)

print(f'O vetor é: {vetor}')
print(f'O modulo do vetor é: {modulo(vetor)}')

Qual a dimensão do vetor?5
O vetor é: [67 46 61 41 69]
O modulo do vetor é: 129.49131244990917


## Questão 3

Em uma **análise de regressão**, usualmente estamos interessados em descrever relações entre variáveis de um dado conjunto de dados por meio de uma **função** que descreva, o tanto quanto possível, estas relações.

Por exemplo, no gráfico abaixo, os pontos vermelhos relacionam as medidas das duas variáveis sendo avaliadas (nos eixos x e y); e a linha azul aproxima a relação entre elas por uma função linear.

![Normdist_regression.png](https://miro.medium.com/v2/resize:fit:786/format:webp/1*LEmBCYAttxS6uI6rEyPLMQ.png)

É possível ver que nem todos os pontos obedecem exatamente à relação ditada pela reta (isto é, há pontos que não estão exatamente "sobre a reta"; mas, sim, ligeraimente acima, ou abaixo, dela). Isto, contudo, é esperado em um modelo de regressão, por inúmeras fontes de incerteza associadas às medições.

Uma das métricas que utilizamos para avaliar a qualidade de uma regressão é o **erro quadrático médio (EQM)**, que mensura a diferença total entre cada predição da regressão ($y_{prediction}$; que no nosso caso seriam os valores de y para a reta azul) com o valor real de cada i-ésima medida ($y_{i}$; que no nosso caso seriam as coordenadas y para cada ponto vermelho do gráfico). O EQM pode ser definido como:

$EQM = \frac{1}{n}\sum_{i=1}^{n}(y_{prediction} - y_{i})^2$.

Isto posto, escreva uma função que calcule o EQM recebendo, como entrada, os vetores $y_{prediction}$ e $y_{i}$. Por exemplo, digamos que sua função se chame *calculate_eqm*, ela deve operar da seguinte forma:

In [ ]:
# Solução
import numpy as np
def calculate_eqm (y_prediction,y_i):
  return (1/y_i.size) * (np.sum((y_prediction-y_i)**2))

y_prediction = np.array([1,2,3])
y_i = np.array([0,0,3])
calculate_eqm(y_prediction,y_i)

1.6666666666666665

## Questão 4

Crie um array 2D (bidimensional) com 1 na borda e 0 dentro

In [ ]:
import numpy as np
dim = int(input('Informe a dimensão da matrix "n X n" (maior que 2):'))
matrix = np.ones((dim, dim), dtype = int)
matrix[1:-1, 1:-1] = 0
print(matrix)

Informe a dimensão da matrix "n X n" (maior que 2):5
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Questão 5

Como adicionar uma borda de 0's ao redor de um array 2D (bidimensional) existente

In [ ]:
import numpy as np
matriz = np.random.randint(1,101, size = (10,10))
nova_matriz = np.pad(matriz, pad_width = 1, constant_values = 0)

print(nova_matriz)

[[ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 69 28 41 90 88 64 26 76 17 38  0]
 [ 0 15 73 85 30 30 26 15 81 93 31  0]
 [ 0 43 87  6 70 42 60 33 40 38 92  0]
 [ 0 96 70 57 90 78 35 53 29 13 79  0]
 [ 0  8 54 70 55 57 71 98 34 25 17  0]
 [ 0 51  6 45 57 80 77 74 56 39 67  0]
 [ 0 85 75 62 59 43 71 70 57 87 58  0]
 [ 0 24 43 87 42 94  2 39 52 48 42  0]
 [ 0 97 74 13 46 99 18 41 98 77 37  0]
 [ 0  4  2 33  3 23  3  9 26  7 28  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]]


## Questão 6

 A eletroencefalografia (EEG) é uma técnica que mensura potenciais elétricos cerebrais em diversas regiões do escalpo do paciente. Suponha que você recebeu um conjunto de dados na forma de uma matriz de 64 x 512 elementos, em que cada linha contém o sinal gravado em um dos **eletrodos** espalhados pelo escalpo em um exame de EEG, e cada coluna contém um valor de potencial elétrico, em microvolts. 

Como o sinal de EEG é muito suscetível a ruídos externos (interferências na qualidade do sinal), uma operação comum para atenuar a interferência no sinal consiste em tirar a média do potencial elétrico de todos os eletrodos, e subtrair este valor de cada um deles. Isto atenua fontes de ruído ao sinal comuns a todos os eletrodos. Em termos matemáticos, o sinal processado por esta operação, $X_{e,i}$ para cada eletrodo (e) e amostra (i), é dado por:

$X_{e,i} = \hat{X_{e,i}} - \frac{1}{N}\sum_{e=1}^{N}\hat{X_{e,i}}$,

em que $\hat{X_{e,i}}$ representa o sinal original (ou seja, é a matriz de entrada de 64 x 512 elementos), e $N$ indica o total de eletrodos.

Com o exposto acima, escreva uma função que retorne uma matriz com os sinais de EEG processados conforme a operação mencionada. Sua função deve operar conforme o exemplo abaixo.

In [ ]:
# Solução
import numpy as np

def process_EEG_signal(X):
  return X-((1/X.shape[0]) * np.sum(X))

X = np.random.randn(64,512)
X_processado = process_EEG_signal(X)

print(X)
print('\n')
print(X_processado)

[[-1.07411893 -0.52663344  0.7011298  ...  1.2067352   0.92179941
   0.78918574]
 [ 2.30151768  1.07661759 -0.849317   ... -0.76956871  1.16713684
  -0.92389715]
 [-1.44733711 -0.86674539  0.76873665 ...  0.38998586 -1.08694532
   1.32137111]
 ...
 [-0.18930665 -0.20107958 -0.2647595  ...  0.76005067  0.72703554
  -0.90600215]
 [ 0.77303459 -1.06898991 -0.81355315 ... -0.43489262 -0.51101035
   1.22096185]
 [-0.21424977 -0.37309086  1.12880514 ...  1.41374069 -0.60552669
   0.31540017]]


[[-3.63598282 -3.08849733 -1.86073409 ... -1.35512869 -1.64006448
  -1.77267815]
 [-0.26034621 -1.4852463  -3.41118089 ... -3.3314326  -1.39472705
  -3.48576104]
 [-4.009201   -3.42860928 -1.79312724 ... -2.17187803 -3.64880921
  -1.24049278]
 ...
 [-2.75117054 -2.76294346 -2.82662339 ... -1.80181322 -1.83482835
  -3.46786604]
 [-1.7888293  -3.6308538  -3.37541703 ... -2.99675651 -3.07287424
  -1.34090204]
 [-2.77611366 -2.93495475 -1.43305875 ... -1.14812319 -3.16739058
  -2.24646372]]


## Questão 7

Em estatística, um **outlier** é um valor que destoa consideravelmente da distribuição à qual está associado. Um dos critérios para idenficar outliers consiste em encontrar a **distância interquantil** (IQR), ou seja, a diferença entre o terceiro (Q3) e o primeiro quartis (Q1) da distribuição, e tomar como outliers todos os pontos abaixo de 1.5*IQR - Q1, ou acima de 1.5*IQR + Q3.

<img src = "https://blog.curso-r.com/images/posts/banner/outlier.webp" />

Escreva uma função que, dada uma matriz de dados de entrada de dimensões $N_{observações} \times N_{features}$ retorne três requisitos: 
- uma matriz booleana indicando a existência de outliers nos dados de entrada;
- a quantidade de outliers
- quem são os outliers (os valores).

**Algumas definições:**
- um *quantil* divide a distribuição, após ordenados os pontos, segundo algum ponto de corte;
- o **primeiro quartil** é o ponto para o qual 25 % dos valores da distribuição estão abaixo dele;
- o **terceiro quartil** é o ponto para o qual 75 % dos valores da distribuição estão abaixo dele.

Pode ser útil consultar a função **numpy.quantile**.

Exemplo de operação da função:

In [ ]:
# Geremos um conjunto de dados qualquer
X = np.random.randn(300,15)
X

array([[-2.02108952,  0.57945921, -2.23074965, ..., -0.60349514,
         0.92180452, -0.15625722],
       [ 0.24904397,  0.03493447,  0.3515052 , ..., -0.46950081,
         0.20361331,  0.02715956],
       [ 0.55902525, -0.48435434,  0.90413414, ..., -0.54425743,
        -0.80769134, -0.07912549],
       ...,
       [-1.04069388, -0.24245725, -2.00308877, ...,  0.4084777 ,
        -1.81516131,  0.39063118],
       [-1.39275097,  0.3989636 ,  0.2926223 , ...,  1.2620666 ,
         0.72262949,  1.50737559],
       [ 0.15922011, -0.79810788, -1.60939896, ..., -0.08214499,
        -0.13167475,  0.15990558]])

In [ ]:
# identificamos os requisitos com nossa com nossa função "locate_outliers"
is_outlier, outliers_count, outliers = locate_outliers(X)

In [ ]:
is_outlier

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [ ]:
outliers_count

44

In [ ]:
outliers

array([-2.67240384,  3.00270904,  3.62317101,  3.18867865,  2.55581522,
       -2.82091429,  2.8757892 ,  2.70666036,  3.19514999, -3.40550318,
       -3.39825827,  2.6727295 ,  2.54498296, -2.69447104,  3.19521603,
        2.66372172, -2.77444948,  2.77421152,  2.69992869, -2.84831109,
       -2.83695779, -2.45908227,  3.07802106,  2.89314015, -2.68574682,
       -2.85019494,  2.43399574,  2.44291266, -2.92595937, -2.95911074,
       -3.03966003,  2.77543068, -2.67368414, -2.79965402, -3.0501958 ,
       -2.5437387 ,  3.08550649, -3.17666255, -3.05795476, -3.09826467,
        3.1399469 ,  3.18141942,  2.90564257, -2.89505054])

In [ ]:
def locate_outliers(X):
  quartil_25 = np.quantile(a, 0.25)
  print(f'Primeiro quartil (25%): {quartil_25}')
  quartil_75 = np.quantile(a, 0.75)
  print(f'Terceiro quartil (75%): {quartil_75}')
  is_outlier = np.where(((X > quartil_25) & (X < quartil_75)), True, False)
  outliers_count = np.count_nonzero(X*is_outlier)
  outliers = X[((X > quartil_25) & (X < quartil_75))]
  return is_outlier, outliers_count, outliers

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
is_outlier, outliers_count, outliers = locate_outliers(a)

[[1 2 3]
 [4 5 6]]
Primeiro quartil (25%): 2.25
Terceiro quartil (75%): 4.75


In [ ]:

is_outlier

array([[False, False,  True],
       [ True, False, False]])

In [ ]:

outliers_count

2

In [ ]:

outliers

array([3, 4])

In [ ]:
# Solução
import numpy as np

def locate_outliers(X):
  Q1 = np.quantile(X, 0.25)
  Q3 = np.quantile(X, 0.75)
  IQR = Q3 - Q1
  limite_inferior = Q1 - 1.5*IQR
  limite_superior = Q3 + 1.5*IQR
  is_outlier = ((X < limite_inferior) | (X > limite_superior))
  outliers_count = np.count_nonzero(is_outlier)
  outliers = X[((X < limite_inferior) | (X > limite_superior))]
  return is_outlier, outliers_count, outliers

X = np.random.randn(300,15)
is_outlier, outliers_count, outliers = locate_outliers(X)

print(f'Quem são os outliers:\n{is_outlier}\n')
print(f'O numero de outliers é: {outliers_count}\n')
print(f'Valores dos outliers:\n {outliers}')

Quem são os outliers:
[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]

O numero de outliers é: 38

Valores dos outliers:
 [ 3.28280879  2.9202697  -2.90067669  3.78625504 -2.83622031 -2.85882429
  3.14669135 -2.74172739 -3.84459506  3.26586487 -2.84141026 -2.846613
 -2.75090833 -2.91644431 -2.82031962  3.11023039 -2.72084094  2.92598872
 -3.20770677  3.07721523  2.79228615  2.88692133 -3.42011129  2.72909503
  3.08870023 -2.76190534  2.79795161  2.81521634  2.8783516   3.34447044
  2.80091248  3.67390079 -2.79341981 -3.03022358 -3.37199947 -3.63159543
 -2.74051972  3.06914733]


## Questão 8

Crie um vetor com valores que vão de 1 até 21 de dois em dois, a partir da função arange

In [ ]:
import numpy as np

print(np.arange(1, 22, 2))

[ 1  3  5  7  9 11 13 15 17 19 21]


## Questão 9

Crie um array de 10 com valores aleatórios

In [ ]:
import numpy as np

_array = np.random.rand(10)

print(_array)

[0.56457793 0.87895641 0.94563522 0.8589072  0.40287759 0.63675919
 0.46477032 0.36644791 0.25070995 0.44150793]


## Questão 10

Em estatística, a normalização de uma distribuição de dados pode ser feita subtraindo o valor médio da distribuição de cada valor do conjunto de dados, dividindo o resultado pelo desvio-padrão da distribuição. Escreva uma função que normalize os dados recebidos por um array numpy qualquer, conforme descrito anteriormente.

In [ ]:
import numpy as np

def normalização(_array):
  media = np.mean(_array)
  std = np.std(_array)
  return (_array - media) / std

_array = np.random.randint(0,10,5)

print(_array)
print(normalização(_array))

[9 2 9 6 7]
[ 0.93138063 -1.78514621  0.93138063 -0.23284516  0.15523011]


## Questão 11

Escreva uma função em numpy que receba um array contendo notas de uma turma de 100 estudantes. Considere que a nota de aprovação da turma é 5.0. A função deve retornar, em um array numpy, nesta ordem:
- a média e o desvio-padrão das notas da turma;
- o número de notas maiores que 7.0;
- o número de reprovações da turma;
- a menor nota da turma;
- a maior nota da turma.

In [ ]:
import numpy as np

notas = np.random.rand(100)*10

def calculos_nota(notas):
  media = np.mean(notas)
  desv_padrao = np.std(notas)
  maiores_7 = np.sum(~(notas < 7))
  menor_notas = np.amin(notas)
  maior_notas = np.amax(notas)
  return media, desv_padrao, maiores_7, menor_notas, maior_notas

media, desv_padrao, maiores_7, menor_notas, maior_notas = calculos_nota(notas)
print(f'A média das notas é: {round(media, 2):.2f}')
print(f'O desvio padrão das notas é: {round(desv_padrao, 2):.2f}')
print(f'A quantidade de notas maior que 7 é: {maiores_7}')
print(f'A menor nota é: {round(menor_notas, 2):.2f}')
print(f'A maior nota é: {round(maior_notas, 2):.2f}')

A média das notas é: 5.09
O desvio padrão das notas é: 2.96
A quantidade de notas maior que 7 é: 35
A menor nota é: 0.10
A maior nota é: 9.93
